import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "@/global.css";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Footer from "@/components/Footer";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frost App",
  description: "Generated by create next app",
};

const appData = {
  serversJoined: 100,
  botUsers: 5000,
  eliteUsers: 100,
  websiteVisits: 5000,
  appCommands: 120,
};

const usefullLinks = [
  {
    label: "Website Map",
    links: [
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
    ],
  },
  {
    label: "Example Title",
    links: [
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
    ],
  },
  {
    label: "Socials",
    links: [
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
      {
        title: "link",
        href: "/link",
      },
    ],
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Navbar />
          {children}
          <Footer appData={appData} usefullLinks={usefullLinks} />
        </ThemeProvider>
      </body>
    </html>
  );
}
