import "@/global.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/i18n.config";
import { DM_Sans } from "next/font/google";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frost App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const appData = {
  serversJoined: 100,
  botUsers: 5000,
  eliteUsers: 100,
  websiteVisits: 5000,
  appCommands: 123,
};

const usefullLinks = [
  {
    label: "Website Map",
    links: [
      {
        title: "Membership",
        href: "/membership",
      },
      {
        title: "Dashboard",
        href: "/dashboard",
      },
      {
        title: "Documentation",
        href: "/docs",
      },
      {
        title: "Join The Elite",
        href: "/elite",
        badge: {
          label: "VIP",
          color: "bg-amber-600/10 text-amber-400",
        },
      },
      {
        title: "Commands",
        href: "/commands",
      },
    ],
  },
  {
    label: "Policy",
    links: [
      {
        title: "Terms Of Use",
        href: "/terms-of-use",
      },
      {
        title: "Privacy Policy",
        href: "/privacy-policy",
      },
      {
        title: "Refund Policy",
        href: "/refund-policy",
      },
    ],
  },
];

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={font.className}>
        <ThemeProvider attribute="class" forcedTheme="dark">
          <Navbar />
          {children}
          <Footer appData={appData} usefullLinks={usefullLinks} />
        </ThemeProvider>
      </body>
    </html>
  );
}
