// TODO: Review and Refactor all app
import "@/global.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/i18n.config";
import { DM_Sans } from "next/font/google";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

import { getDictionary } from "@/lib/dictionary";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frost App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const { usefullLinks, rights, navbar, userMenu } = await getDictionary(
    params.lang
  );

  const appData = {
    serversJoined: 100,
    botUsers: 5000,
    eliteUsers: 100,
    websiteVisits: 5000,
    appCommands: 123,
  };

  return (
    <html lang={params.lang}>
      <body className={font.className}>
        <ThemeProvider attribute="class" forcedTheme="dark">
          <Navbar navbar={navbar} userMenu={userMenu} />
          {children}
          <Footer
            rights={rights}
            appData={appData}
            usefullLinks={usefullLinks}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
